### ISSUE TITLE
is there a way to pass additional params to addvote method ?

### ISSUE THREAD

**Issue by skakrecha** [ppietris/vue-poll#1]
Hi first of all you have made a great package, works awesome ! i want to use it one of my hobby projects where i have different posts having polls, i need to pass that post id in the addvote method so that i can insert it in the backend. can u help with this if it s already possible ? thanks

**Comment by ppietris** [comment]
Hello skakrecha

A new option (**customId**) was added. You can pass your postId there.

Thanks
