### ISSUE TITLE
How to allow multiple vote?

### ISSUE THREAD

**Issue by PhouvanhKCSV** [ppietris/vue-poll#2]
Is it possible to make multiple vote?

**Comment by ppietris** [comment]
Not yet. It could be on the next update!

**Comment by PhouvanhKCSV** [comment]
Thank you

**Comment by ppietris** [comment]
@PhouvanhKCSV 

Multiple voting is available.
Set the **multiple** attribute to true and add **selected: false** to all your answers

**Comment by PhouvanhKCSV** [comment]
It works fine. Thank you again to create this helpful function.
