### ISSUE TITLE
Selected vote not showing if finalResults

### ISSUE THREAD

**Issue by yamenarahman** [ppietris/vue-poll#5]
Selected tick or check is showing up with showResults but not with finalResults.

**Comment by ppietris** [comment]
Hello Yamen.

Both **showResults** and **finalResults** indicate that a voting has ended and were added for show purposes. Correct me if I'm wrong, but I don't think that any of these properties (if true) allow the user to vote. That's the reason the check/tick is not visible.

 Thanks!
