### ISSUE TITLE
Formatting challenges

### ISSUE THREAD

**Issue by ChaStPierre** [ppietris/vue-poll#6]
I'm trying to format the answers vie the custom_class which does not seem to be working. Might be an issue or just need more documentation. It would also be great to format additional elements including questions and finalresuts.

Thanks

**Comment by ppietris** [comment]
@ChaStPierre 
**custom_class** can be used as an attribute on an answer (for styling).

For example:
```javascript
answers: [ 
     { value: 1, text: 'Vue', votes: 53, custom_class: 'my-vue-class' },
     { value: 2, text: 'React', votes: 35, custom_class: 'my-react-class' },
     { value: 3, text: 'Angular', votes: 30, custom_class: 'my-angular-class' },
     { value: 4, text: 'Other', votes: 10, custom_class: 'my-class' } 
]
```

You can target via CSS and style:
Questions : 
```css
.vue-poll .qst {}
```

Answers: 
```css
.vue-poll .ans-cnt .ans {}

/*custom_class from the above example*/
.vue-poll .ans-cnt .ans.my-vue-class {}
```

Final results per answer: 
```css
.vue-poll .ans-cnt .ans .ans-voted {}
```

**Comment by ChaStPierre** [comment]
Thanks for the quick response. Note that css props would be very helpful when used with a presentation library like Vuetify or others.
